#!/bin/bash


ECG='\[\033[1;32m\]'
ECB='\[\033[1;34m\]'
ECY='\[\033[1;33m\]'
ECV='\[\033[1;31m\]'
EBEL='\007\]'
ET='\[\033]0;'

TITLE="$ET$SCR$SB_NAME \W$EBEL"
GIT_BRANCH='$(__git_ps1 "[%s] ")'
if [ "x$PS_STR" == "x" ] ; then
	PS1="$TITLE$ECB\h: \w\n$\[\033[0m\] "
	PS1="$TITLE$ECY$GIT_BRANCH$ECB\w\n$\[\033[0m\] "
else
	PS1="$TITLE$ECB$PS_STR$ECY$GIT_BRANCH$ECB: \w\n$\[\033[0m\] "
fi

PATH=$PATH:$HOME/local/bin

[ -e "$HOME/QSTK/config.sh" ] && source $HOME/QSTK/config.sh
export WORKON_HOME=$HOME/domains
export PIP_VIRTIALENV_BASE=$

alias cdbase='cd `git rev-parse --show-cdup`'

export PATH=$PATH:$HOME/src/algs4/bin

#[ -n "$VIRTUAL_ENV" ] && source $VIRTUAL_ENV/bin/activate 
